Demo/Controllers/CourseController.cs
using Demo.Infrastructure;
using Demo.Models.Entities;
using Demo.Models.Interfaces;
using Demo.Models.Repository;
using Demo.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Demo.Controllers;


public class CourseController : Controller
{

    private ICourseRepository CourseRepository;
    private IInstructorRepository InstructorRepository;
    private IDepartmentRepository DepartmentRepository;

    public CourseController(
        ICourseRepository courseRepository, 
        IDepartmentRepository departmentRepository,
        IInstructorRepository instructorRepository
        )
    {
        CourseRepository = courseRepository;
        DepartmentRepository = departmentRepository;
        InstructorRepository = instructorRepository;
    }

      [HttpGet]
    //[Route("courses")] -> this route has higher priority than the routing in the program.cs
    public IActionResult Index()
    {
        List<Course> courses = CourseRepository.Load();
        List<string> Errors = new List<string>();
        List<Department> departments = DepartmentRepository.Load();
        List<Instructor> instructors = InstructorRepository.Load();


        if (courses is null)
        {
            Errors.Add("Cannot fetch courses from the database");
            ViewBag.Errors = Errors;
            return RedirectToAction("Index", "Home");
        }

        ViewBag.Departments = departments;
        ViewBag.Instructors = instructors;
        return View("Index", courses);
    }



    public IActionResult AddCourse()
    {

        CourseViewModel courseView = new CourseViewModel();

        var instructors = InstructorRepository.LoadSelectItems();

        courseView.Instructors = instructors;
        courseView.Departments = DepartmentRepository.Load();

        return View("AddCourse", courseView);
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult AddCourse(int id,CourseViewModel CourseView)
    {
        CourseView.Departments = DepartmentRepository.Load();
        CourseView.Instructors = InstructorRepository.LoadSelectItems();

        if (ModelState.IsValid) //server side validation
        {
            try
            {
                var course = new Course
                {
                    Name = CourseView.Name,
                    Degree = CourseView.Degree,
                    MinDegree = CourseView.MinDegree,
                    DeptId = CourseView.DeptId,
                    Instructors = InstructorRepository.LoadInstructorsWithTheirCourses(CourseView, false)
                };

                int oldCourseCount = CourseRepository.Count();

                CourseRepository.Insert(course);

                int newCourseCount = CourseRepository.Count();

                if (newCourseCount > oldCourseCount)
                    TempData["Message"] = "Course Added Successfully";
                else 
                    TempData["Message"] = string.Empty;

                
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
        }
        return View(CourseView);
    }
    [HttpGet]
    public IActionResult Edit(int id)
    {
        CourseViewModel courseView = new CourseViewModel();
        var course = CourseRepository.Get(id);


        var instructors = InstructorRepository.LoadSelectItems();

        courseView.Instructors = instructors;
        courseView.Departments = DepartmentRepository.Load();
        courseView.Name = course.Name;
        courseView.DeptId = course.DeptId;
        courseView.Id = course.Id;
        courseView.Degree = course.Degree;
        courseView.MinDegree = course.MinDegree;

        return View("Edit", courseView);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(int id, CourseViewModel newCourse)
    {
        var oldCourse = CourseRepository.Get(id);

        newCourse.Departments = DepartmentRepository.Load();
        newCourse.Instructors = InstructorRepository.LoadSelectItems();

        oldCourse.Name = newCourse.Name;
        oldCourse.DeptId = newCourse.DeptId;
        oldCourse.Degree = newCourse.Degree;
        oldCourse.MinDegree = newCourse.MinDegree;
        oldCourse.Instructors = InstructorRepository.LoadInstructorsWithTheirCourses(newCourse, true);

        return RedirectToAction("Index");
    }

    public JsonResult IsValidMinDegree(decimal minDegree, decimal degree)
    {
        if(minDegree < degree)
            return Json(true);
        else
            return Json("Minimum Degree must be less than the degree you entered");
    }

    [HttpGet]
    public IActionResult CourseDetails(int id)
    {
        var course = CourseRepository.Get(id);
        var instructors = InstructorRepository.Load();
        
        course.Instructors = instructors;

        return PartialView("CourseDetailsPartial", course);
    }
}

Demo/Controllers/InstructorController.cs
using Demo.Infrastructure;
using Demo.Models.Entities;
using Demo.Models.Interfaces;
using Demo.Models.Repository;
using Demo.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace Demo.Controllers
{
    [Authorize(Roles = "Admin")]
    public class InstructorController : Controller
    {

        private ICourseRepository CourseRepository;
        private IInstructorRepository InstructorRepository;
        private IDepartmentRepository DepartmentRepository;

        public InstructorController(
            ICourseRepository courseRepository, 
            IInstructorRepository instructorRepository,
            IDepartmentRepository departmentRepository
            )
        {
            CourseRepository = courseRepository;
            InstructorRepository = instructorRepository;
            DepartmentRepository = departmentRepository;
        }

        public IActionResult Index()
        {
            List<Instructor> instructors = InstructorRepository.Load();

            return View(instructors);

        }

        public IActionResult GetInstructor(int id)
        {
            List<Instructor> instructors = InstructorRepository.Load();

            var instructor = InstructorRepository.Get(id);

            return View(instructor);
        }

        public IActionResult Edit(int id)
        {
            List<Instructor> instructors = InstructorRepository.Load();
            var instructor = InstructorRepository.Get(id);
            return View(instructor);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Save(Instructor newInstructor)
        {
            List<Instructor> instructors = InstructorRepository.Load();
            var oldInstructor = InstructorRepository.Get(newInstructor.Id);

            if(newInstructor is null)
                return RedirectToAction("Edit");

            if (newInstructor.Name == null || newInstructor.Image == null)
                return RedirectToAction("Edit");

            InstructorRepository.Update(oldInstructor, newInstructor);
            //InstructorRepository.Update(newInstructor.Id, oldInstructor);

            TempData["success"] = true;
            return RedirectToAction("Index");
        }


        public IActionResult addInstructor()
        {
            List<Course> courses = CourseRepository.Load();
            List<Department> departments = DepartmentRepository.Load();

            var instructorVm = new InstructorViewModel();
            instructorVm.courses = courses;
            instructorVm.departments = departments;

            return View(instructorVm);
        }
         
        public IActionResult SuccessAdd(InstructorViewModel newInstructorvm)
        {

            var newInstructor = new Instructor
            {
                Id = newInstructorvm.Id,
                Name = newInstructorvm.Name,
                Image = newInstructorvm.Image,
                Salary = newInstructorvm.Salary,
                Address = newInstructorvm.Address,
                CourseId = newInstructorvm.CourseId,
                DeptId = newInstructorvm.DeptId,
                Course = newInstructorvm.Course,
                Department = newInstructorvm.Department,
            };


            var department = DepartmentRepository.Get(newInstructor.DeptId);

            newInstructor.Department = department;
            InstructorRepository.Insert(newInstructor);
            TempData["success"] = true;

            return RedirectToAction("Index");
        }

        //creating action to show the courses for that depeartment
        public IActionResult ShowCoursesPerDept(int deptId)
        {
            var department = DepartmentRepository.Get(deptId);
            var allCourses = CourseRepository.Load();


            var itemList = allCourses.Where(c => c.DeptId == deptId).ToList();

            var ivm = new InstructorViewModel
            {
                itemList = itemList,
            };
            
            return PartialView("ShowCoursesPerDeptPartial",ivm);
        }

        public IActionResult ShowSuccess()
        {
            return View("_ShowSuccessPartial");
        }
    }
}

//goal - display the courses for the selected department using ajax

Demo/Controllers/TraineeController.cs
using Demo.Models.Entities;
using Demo.Models.Interfaces;
using Demo.Models.Repository;
using Demo.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace Demo.Controllers
{
    public class TraineeController : Controller
    {
        private ITraineeRepository _traineeRepository;
        private IDepartmentRepository _departmentRepository;
        public TraineeController(ITraineeRepository traineeRepository, IDepartmentRepository departmentRepository) 
        {
            _traineeRepository = traineeRepository;
            _departmentRepository = departmentRepository;
        }


        [HttpGet]
        public IActionResult Index()
        {
            var trainees = _traineeRepository.Load(true);
            
            return View(trainees);
        }

        [HttpGet]
        public IActionResult AddTrainee()
        {
            var departments = _departmentRepository.Load();
            Console.WriteLine("This is the get action");

            var traineeVm = new TraineeViewModel();
            traineeVm.departments = departments;

            return View(traineeVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddTrainee(TraineeViewModel newTrainee)
        {
            Console.WriteLine("This is the POST action");
            if(ModelState.IsValid)
            {
                Department dept = _departmentRepository.Get(newTrainee.DeptId);

                Trainee trainee = new Trainee
                {
                    Name = newTrainee.Name,
                    Image = newTrainee.Image,
                    Address = newTrainee.Address,
                    Grade = newTrainee.Grade,
                    Department = dept,
                };

                _traineeRepository.Insert(trainee);
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("AddTrainee");
            }
                
        }
    }
}

Demo/Views/Shared/ButtonExamples.cshtml
<!-- Example of buttons with simplified hover effects -->

<div class="container mt-5">
  <h2>Buttons with Simplified Hover Effects</h2>
  <div class="row mt-4">
    <div class="col-md-6">
      <h4>Primary Buttons</h4>
      <div class="mb-3">
        <!-- Default Bootstrap button with our simplified hover effect -->
        <button type="button" class="btn btn-primary me-2">
          Primary Button
        </button>
        
        <!-- With icon -->
        <button type="button" class="btn btn-primary d-inline-flex align-items-center gap-2">
          <i class="bi bi-check"></i>
          With Icon
        </button>
      </div>
      
      <h4>Outline Buttons</h4>
      <div class="mb-3">
        <button type="button" class="btn btn-outline-primary me-2">
          Outline Primary
        </button>
        
        <button type="button" class="btn btn-outline-secondary d-inline-flex align-items-center gap-2">
          <i class="bi bi-arrow-right"></i>
          Outline Secondary
        </button>
      </div>
    </div>
    
    <div class="col-md-6">
      <h4>Secondary Buttons</h4>
      <div class="mb-3">
        <button type="button" class="btn btn-secondary me-2">
          Secondary Button
        </button>
        
        <button type="button" class="btn btn-secondary d-inline-flex align-items-center gap-2">
          <i class="bi bi-gear"></i>
          With Icon
        </button>
      </div>
      
      <h4>Link Buttons</h4>
      <div>
        <button type="button" class="btn btn-link me-2">
          Link Button
        </button>
        
        <button type="button" class="btn btn-link text-decoration-none d-inline-flex align-items-center gap-2">
          <i class="bi bi-link-45deg"></i>
          With Icon
        </button>
      </div>
    </div>
  </div>
</div>

<!-- Note: This example uses Bootstrap Icons. To use them, include the Bootstrap Icons CSS or use Font Awesome instead -->
<!-- Implementation instructions: 
     1. Include the button-simplify.css file after Bootstrap CSS
     2. Use standard Bootstrap button classes with minimal additional classes
     3. For buttons with icons, use the d-inline-flex, align-items-center, and gap-{size} utility classes
-->

Demo/Views/Shared/HeaderPartial.cshtml
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo</title>

    <!-- Bootstrap CSS -->
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    
    <!-- Animate.css for animations -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />

    <!-- Custom CSS -->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    
    <!-- Simplified Button Hover Effects -->
    <link rel="stylesheet" href="~/css/button-simplify.css" asp-append-version="true" />
    
    <!-- Simplified Input Focus Effects -->
    <link rel="stylesheet" href="~/css/input-simplify.css" asp-append-version="true" />
    
    <!-- Label Positioning -->
    <link rel="stylesheet" href="~/css/label-position.css" asp-append-version="true" />
    
    <!-- Navbar Animation Removal -->
    <link rel="stylesheet" href="~/css/navbar-simplify.css" asp-append-version="true" />
    
    <!-- Floating Label Override (must be last) -->
    <link rel="stylesheet" href="~/css/floating-label-override.css" asp-append-version="true" />

    <!-- Add Feather Icons for better UI -->
    <script src="https://unpkg.com/feather-icons"></script>
</head>

Demo/Views/Shared/_FooterPartial.cshtml
<footer class="border-top bg-white text-muted mt-auto">
    <div class="container py-4">
        <div class="row align-items-center">
            <div class="col-md-6">
                <div class="d-flex align-items-center">
                    <i data-feather="heart" class="text-primary me-2" style="width: 16px; height: 16px;"></i>
                    <p class="mb-0">&copy; 2025 - Demo. Made with care.</p>
                </div>
            </div>
            <div class="col-md-6 text-md-end">
                <div class="d-flex justify-content-md-end gap-3">
                    <a class="text-decoration-none d-flex align-items-center"
                       asp-area="" asp-controller="Home" asp-action="Privacy">
                        <i data-feather="shield" class="me-1" style="width: 16px; height: 16px;"></i>
                        Privacy
                    </a>
                    <a href="#" class="text-decoration-none d-flex align-items-center">
                        <i data-feather="mail" class="me-1" style="width: 16px; height: 16px;"></i>
                        Contact
                    </a>
                </div>
            </div>
        </div>
    </div>
</footer>

Demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<partial name="HeaderPartial"/>
<body class="d-flex flex-column min-vh-100">

    <!-- Page Loading Overlay -->
    @* <div class="page-loading" id="pageLoader">
        <div class="page-loading-spinner"></div>
    </div> *@

    <!-- Navbar -->
    <partial name="_NavPartial" />

    <!-- Main -->
    <main role="main" class="flex-grow-1 container py-4">
        <div class="page-content">
            @RenderBody()
        </div>
    </main>

    <!-- Footer -->
    <partial name="_FooterPartial" />

    <!-- jQuery (required for Bootstrap) -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    
    <!-- Bootstrap JavaScript Bundle (includes Popper) -->
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    
    <!-- Custom JavaScript -->
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- Page Transition Script -->
    <script>
        // Page Transition Manager
        class PageTransitionManager {
            constructor() {
                this.loader = document.getElementById('pageLoader');
                this.mainContent = document.querySelector('main[role="main"]');
                this.initializeTransitions();
                this.addNavigationListeners();
            }

            initializeTransitions() {
                // Add transition classes to page elements
                if (this.mainContent) {
                    this.mainContent.classList.add('page-transition');
                }

                // Add stagger animation to cards
                this.addStaggerAnimation();
            }

            addStaggerAnimation() {
                const cards = document.querySelectorAll('.card');
                cards.forEach((card, index) => {
                    card.classList.add('stagger-animation');
                    card.style.animationDelay = `${0.1 + (index * 0.1)}s`;
                });
            }

            showLoader() {
                if (this.loader) {
                    this.loader.classList.add('active');
                }
            }

            hideLoader() {
                if (this.loader) {
                    this.loader.classList.remove('active');
                }
            }

            addNavigationListeners() {
                // Add smooth transitions to navigation links
                const navLinks = document.querySelectorAll('.nav-link[asp-controller], a[asp-controller]');
                
                navLinks.forEach(link => {
                    link.addEventListener('click', (e) => {
                        // Only apply to internal navigation
                        if (!link.getAttribute('href') || link.getAttribute('href').startsWith('#')) {
                            return;
                        }

                        // Show loading animation
                        this.showLoader();

                        // Add a slight delay for visual effect
                        setTimeout(() => {
                            // Let the normal navigation proceed
                        }, 100);
                    });
                });

                // Handle browser back/forward buttons
                window.addEventListener('popstate', () => {
                    this.showLoader();
                    setTimeout(() => this.hideLoader(), 300);
                });
            }

            // Method to manually trigger page transition
            transitionToPage(url) {
                this.showLoader();
                
                setTimeout(() => {
                    window.location.href = url;
                }, 200);
            }
        }

        // Initialize page transitions when DOM is loaded
        document.addEventListener('DOMContentLoaded', function() {
            const transitionManager = new PageTransitionManager();
            
            // Hide loader after page load
            window.addEventListener('load', () => {
                setTimeout(() => {
                    transitionManager.hideLoader();
                }, 500);
            });

            // Apply active state to current nav link
           
        });

        // Initialize Feather Icons
        feather.replace();
        
        function toggleMobileMenu() {
            const menu = document.getElementById('mobileMenu');
            if (menu) {
                menu.classList.toggle('d-none');
            }
        }
        
        // Add smooth scroll behavior
        document.documentElement.style.scrollBehavior = 'smooth';
        
        // this caused a submt problem
        // document.querySelectorAll('form').forEach(form => {
        //     form.addEventListener('submit', function(e) {
        //         const submitBtn = this.querySelector('button[type="submit"]');
        //         if (submitBtn && this.checkValidity()) {
        //             Show loading state with animation
        //             submitBtn.innerHTML = '<div class="spinner-border spinner-border-sm me-2" role="status"></div>Loading...';
        //             submitBtn.disabled = true;
        //             submitBtn.style.transform = 'scale(0.98)';
        //         }
        //     });
        // });
        
        // Force dark theme application with smooth transitions
        document.addEventListener('DOMContentLoaded', function() {
            // Ensure dark theme is applied with transitions
            document.body.style.transition = 'background-color 0.3s ease, color 0.3s ease';
            document.body.style.backgroundColor = 'var(--dark-primary)';
            document.body.style.color = 'var(--text-primary)';
            
            // Add dark theme class to all Bootstrap components with transitions
            document.querySelectorAll('.modal-content, .dropdown-menu, .toast').forEach(element => {
                element.style.transition = 'all 0.3s ease';
                element.style.backgroundColor = 'var(--dark-card)';
                element.style.borderColor = 'var(--dark-accent)';
                element.style.color = 'var(--text-primary)';
            });
        });
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Demo/Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div style="background-color:aqua; height:200px">Header</div>
    <div style="background-color:red; height:200px">Menu
        <div>
            @RenderSection("MenuSection");
        </div>
    </div>

    <div>
        @RenderBody()
    </div>
    <div style="background-color:aqua; height:200px">Footer</div>
</body>
@* <script>
    feather.replace();

    function toggleMobileMenu() {
        const menu = document.getElementById('mobileMenu');
        menu.classList.toggle('hidden');
    }

    // Add smooth scroll behavior
    document.documentElement.style.scrollBehavior = 'smooth';

    // Add loading states for forms
    document.querySelectorAll('form').forEach(form => {
        form.addEventListener('submit', function() {
            const submitBtn = this.querySelector('button[type="submit"]');
            if (submitBtn) {
                submitBtn.innerHTML = '<div class="spinner mr-2"></div>Loading...';
                submitBtn.disabled = true;
            }
        });
    });
</script> *@

@RenderSection("Scripts",false);
</html>

Demo/Views/Shared/_NavPartial.cshtml
@{
    Console.WriteLine(Context.Request.Path.Value);
}
<nav class="navbar navbar-expand-lg navbar-dark shadow-sm mb-4">
    <div class="container">
        <!-- Brand -->
        <a class="navbar-brand fw-bold d-flex align-items-center"
           asp-area="" asp-controller="Home" asp-action="Index">
            <i data-feather="layers" class="me-2 text-primary" style="width: 24px; height: 24px;"></i>
            Demo
        </a>

        <!-- Mobile Menu Button -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" 
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Desktop Nav -->
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center smooth-nav @(Context.Request.Path.Value == "/" || Context.Request.Path.Value?.ToLower().Contains("/home/index") == true ? "active" : "")" 
                       data-page="home"
                       asp-area="" asp-controller="Home" asp-action="Index">
                        <i data-feather="home" class="me-2" style="width: 16px; height: 16px;"></i>
                        Home
                    </a>
                </li>
                @if (User.Identity.IsAuthenticated)
                {
                    if(User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center smooth-nav @(Context.Request.Path.Value?.ToLower().Contains("/instructor") == true ? "active" : "")"
                               data-page="instructors"
                               asp-area="" asp-controller="Instructor" asp-action="Index">
                                <i data-feather="users" class="me-2" style="width: 16px; height: 16px;"></i>
                                Instructors
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link d-flex align-items-center smooth-nav @(Context.Request.Path.Value?.ToLower().Contains("/trainee") == true ? "active" : "")"
                               data-page="trainees"
                               asp-area="" asp-controller="Trainee" asp-action="Index">
                                <i data-feather="users" class="me-2" style="width: 16px; height: 16px;"></i>
                                Trainees
                            </a>
                        </li>
                    }
                    <li class="nav-item">
                        <a class="nav-link d-flex align-items-center smooth-nav @(Context.Request.Path.Value?.ToLower().Contains("/course") == true ? "active" : "")"
                           data-page="courses"
                           asp-area="" asp-controller="Course" asp-action="Index">
                            <i data-feather="book-open" class="me-2" style="width: 16px; height: 16px;"></i>
                            Courses
                        </a>
                    </li>
                }
                <li class="nav-item">
                    <a class="nav-link d-flex align-items-center smooth-nav @(Context.Request.Path.Value?.ToLower().Contains("/home/privacy") == true ? "active" : "")"
                       data-page="privacy"
                       asp-area="" asp-controller="Home" asp-action="Privacy">
                        <i data-feather="shield" class="me-2" style="width: 16px; height: 16px;"></i>
                        Privacy
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">                    
                @if(User.Identity.IsAuthenticated == false)
                {
                    <li class="nav-item">
                        <a class="nav-link d-flex align-items-center smooth-nav @(Context.Request.Path.Value?.ToLower().Contains("/account/login") == true ? "active" : "")"
                           data-page="login"
                           asp-area="" asp-controller="Account" asp-action="Login">
                            <i data-feather="log-in" class="me-2" style="width: 16px; height: 16px;"></i>
                            Login
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link d-flex align-items-center smooth-nav @(Context.Request.Path.Value?.ToLower().Contains("/account/register") == true ? "active" : "")"
                           data-page="register"
                           asp-area="" asp-controller="Account" asp-action="Register">
                            <i data-feather="user-plus" class="me-2" style="width: 16px; height: 16px;"></i>
                            Register
                        </a>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link d-flex align-items-center smooth-nav @(Context.Request.Path.Value?.ToLower().Contains("/account/logout") == true ? "active" : "")"
                           data-page="logout"
                           asp-area="" asp-controller="Account" asp-action="Logout">
                            <i data-feather="log-out" class="me-2" style="width: 16px; height: 16px;"></i>
                            Logout
                        </a>
                    </li>
                    <li class="nav-item d-flex align-items-center px-3">
                        <div class="d-flex align-items-center">
                            <i data-feather="user" class="me-2" style="width: 16px; height: 16px;"></i>
                            <span class="text-light">Hello, @User.Identity.Name</span>
                        </div>
                    </li>
                }
            </ul>
        </div>
    </div>
</nav>

Demo/Views/Shared/_RegisterPagePartial.cshtml
 <!-- Username Field -->
@model Demo.ViewModel.RegisterViewModel

<div class="modern-input-group mb-4">
    <input asp-for="Username"
           class="modern-input"
           id="username"
           placeholder=" "
           autocomplete="off" />
    <label for="username" class="modern-label">
        <span>Username</span>
    </label>
    <span asp-validation-for="Username" class="validation-error"></span>
</div>

<!-- Password Field -->
<div class="modern-input-group mb-4">
    <input asp-for="Password"
           class="modern-input"
           id="password"
           placeholder=" "
           autocomplete="off" />
    <label for="password" class="modern-label">
        <span>Password</span>
    </label>
    <span asp-validation-for="Password" class="validation-error"></span>
</div>

<!-- Confirm Password Field -->
<div class="modern-input-group mb-4">
    <input asp-for="ConfirmPassword"
           class="modern-input"
           id="confirmPassword"
           placeholder=" "
           autocomplete="off" />
    <label for="confirmPassword" class="modern-label">
        <span>Confirm Password</span>
    </label>
    <span asp-validation-for="ConfirmPassword" class="validation-error"></span>
</div>

<!-- Address Field -->
<div class="modern-input-group mb-4">
    <input asp-for="Address"
           class="modern-input"
           id="address"
           placeholder=" "
           autocomplete="off" />
    <label for="address" class="modern-label">
        <span>Address</span>
    </label>
    <span asp-validation-for="Address" class="validation-error"></span>
</div>